# Kaspa Stratum Bridge Configuration Example

# Stratum server settings
stratum_port: ":35555"  # Port for stratum server to listen on
kaspad_address: "127.0.0.1:16110"  # Kaspad RPC server address

# Monitoring settings
prom_port: ":2114"  # Prometheus metrics port
print_stats: true  # Print mining statistics to console
log_to_file: true  # Log to file instead of console
health_check_port: ":18080"  # Health check endpoint port

# Mining settings
block_wait_time: 2s  # Time to wait between block template updates
min_share_diff: 4  # Minimum share difficulty
var_diff: true  # Enable variable difficulty
shares_per_min: 20  # Target shares per minute for vardiff
var_diff_stats: true  # Print vardiff statistics
extranonce_size: 2  # Size of extranonce (max 3)
pow2_clamp: true  # Clamp difficulty to power of 2

# RPC Pool Configuration
rpc_pool_config:
  pool_size: 3  # Number of RPC connections to maintain (default: 3)
  health_check_interval: 30s  # How often to check connection health (default: 30s)
  reconnect_delay: 5s  # Delay between reconnection attempts (default: 5s) 
